### ISSUE TITLE
Defect: launch.sh modify the .bashrc which lead to the -bash: .: filename argument required

### ISSUE THREAD

**Issue by xunavy** [morningspace/lab-k8s-playground#1]
test env :Red Hat Enterprise Linux Server release 7.6 (Maipo)
we tried to follow this step:
You can also launch the playground on your host machine directly by running below command in repository root directory to initialize the environment at first:
$ ./install/launch.sh init
It will modify .bashrc in user home directory.
$ . ~/.bashrc
When we relogin the server ,and got the below error:
root@9.46.76.127's password:
Last login: Tue Sep 10 20:57:10 2019 from 9.119.157.47
-bash: .: filename argument required
.: usage: . filename [arguments]
bash: EXPORT: command not found...

**Comment by morningspace** [comment]
Thanks @xunavy RHEL hasn't been fully tested yet. I am going to find a RHEL server to test. The playground currently supports Ubuntu, CentOS, and MacOS.

**Comment by xunavy** [comment]
check the ~/.bashrc which is modified by launch.sh init, we find that :
1. comments below:
if [ -f  ]; then
   .
fi
2.change "EXPORT skip_snapshot=1 " to "export skip_snapshot=1"

**Comment by morningspace** [comment]
Issue has been fixed. Now, the playground officially supports RHEL:-)
Please `git pull` the latest playground from master branch and see if it's working. @xunavy
Feel free to reopen if it doesn't...
